project_id = "tkuhlxymbnakdaaejbjv"

[functions.asaas-create-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-create-withdrawal]
verify_jwt = false

[functions.asaas-check-payment]
verify_jwt = false
